#!/usr/bin/env python3
"""One-command readiness check for an agentic workflow setup.

Read-only: inspects the repo, PATH, and Claude Code plugin/skill locations,
then prints an ordered do-this-next list with exact commands. It never
installs, edits config, or writes files — installs stay approval-first.

    python3 <skill-dir>/scripts/preflight.py --project-root .

Safe on existing codebases: it only reports what is present and what is
missing. The only commands it runs are read-only (`git status --porcelain`,
`claude plugin list --json`).
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

BOOTLOADER_MARKER = "ultimate-agentic-workflow"
KIT_AGENTS = ["code-reviewer", "skeptic-verifier", "test-runner", "researcher", "implementer"]

SUPERPOWERS_INSTALL = "/plugin install superpowers@claude-plugins-official   (inside Claude Code)"
GSD_CORE_INSTALL = "npx @opengsd/gsd-core@latest"


def load_sibling(name: str):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).with_name(f"{name}.py"))
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def run_quiet(command: list[str], timeout: int = 10) -> str | None:
    try:
        result = subprocess.run(command, text=True, capture_output=True, timeout=timeout)
    except Exception:
        return None
    return result.stdout if result.returncode == 0 else None


def file_role(path: Path) -> str:
    """'missing', 'ours' (generated by this skill), or 'foreign'."""
    if not path.is_file():
        return "missing"
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "foreign"
    return "ours" if BOOTLOADER_MARKER in content else "foreign"


def stop_gate_wired(root: Path) -> bool:
    """True only if .claude/settings.json actually wires the stop-gate hook."""
    settings = root / ".claude" / "settings.json"
    try:
        data = json.loads(settings.read_text(encoding="utf-8"))
    except Exception:
        return False
    for group in (data.get("hooks", {}) or {}).get("Stop") or []:
        if not isinstance(group, dict):
            continue
        for hook in group.get("hooks") or []:
            if isinstance(hook, dict) and "stop_gate.py" in str(hook.get("command", "")):
                return True
    return False


def check_repo(root: Path) -> dict:
    git_dir = (root / ".git").exists()
    dirty = None
    if git_dir:
        status = run_quiet(["git", "-C", str(root), "status", "--porcelain"])
        dirty = bool(status.strip()) if status is not None else None

    kit_agents_present = [
        name for name in KIT_AGENTS if (root / ".claude" / "agents" / f"{name}.md").is_file()
    ]
    bootloader_claude = file_role(root / "CLAUDE.md")
    bootloader_codex = file_role(root / "AGENTS.md")
    ops = file_role(root / "OPS.md")
    # v1 of this skill gave AGENTS.md the operational-guide role for Claude
    # repos (v2 moved that to OPS.md). Signature: our CLAUDE.md bootloader,
    # an AGENTS.md that reads like the old ops guide, and no OPS.md.
    agents_md = root / "AGENTS.md"
    v1_claude_layout = (
        bootloader_claude == "ours"
        and bootloader_codex == "foreign"
        and ops == "missing"
        and agents_md.is_file()
        and "Operational" in agents_md.read_text(encoding="utf-8", errors="replace")
    )
    return {
        "git_repo": git_dir,
        "git_dirty": dirty,
        "bootloader_claude": bootloader_claude,
        "bootloader_codex": bootloader_codex,
        "ops": ops,
        "v1_claude_layout": v1_claude_layout,
        "claude_settings": (root / ".claude" / "settings.json").is_file(),
        "kit_agents_present": kit_agents_present,
        "kit_hooks_present": (root / ".claude" / "hooks" / "stop_gate.py").is_file(),
        "kit_skills_present": (root / ".claude" / "skills" / "retro" / "SKILL.md").is_file(),
        "stop_gate_wired": stop_gate_wired(root),
        "stop_gate_configured": (root / ".claude" / "stop-gate.json").is_file(),
        "workflow_runs": (root / ".workflow").is_dir(),
    }


def detect_superpowers(home: Path) -> dict:
    """Detect the obra/superpowers Claude Code plugin (exact-name match)."""
    detected_via = None
    listing = run_quiet(["claude", "plugin", "list", "--json"]) if shutil.which("claude") else None
    if listing:
        try:
            plugins = json.loads(listing)
            names = {
                str(p.get("name", "")) for p in plugins if isinstance(p, dict)
            } if isinstance(plugins, list) else set()
            if "superpowers" in names:
                detected_via = "claude plugin list"
        except json.JSONDecodeError:
            pass
    if not detected_via:
        cache = home / ".claude" / "plugins" / "cache"
        if cache.is_dir() and any(cache.glob("*/superpowers/*")):
            detected_via = "plugin cache"
    if not detected_via:
        settings = home / ".claude" / "settings.json"
        try:
            enabled = json.loads(settings.read_text(encoding="utf-8")).get("enabledPlugins", {})
            if any(str(key).split("@")[0] == "superpowers" for key in enabled):
                detected_via = "enabledPlugins"
        except Exception:
            pass
    return {"installed": bool(detected_via), "detected_via": detected_via, "install": SUPERPOWERS_INSTALL}


def detect_gsd(root: Path, home: Path) -> dict:
    """Detect GSD (original get-shit-done or the open-gsd successor)."""
    signals = []
    if (root / ".planning" / "config.json").is_file():
        signals.append("project .planning/config.json")
    if (home / ".gsd" / "defaults.json").is_file():
        signals.append("~/.gsd/defaults.json")
    skills = home / ".claude" / "skills"
    if skills.is_dir() and any(skills.glob("gsd-*")):
        signals.append("~/.claude/skills/gsd-*")
    return {
        "installed": bool(signals),
        "detected_via": ", ".join(signals) or None,
        "install": GSD_CORE_INSTALL,
        "note": (
            "The original gsd-build/get-shit-done repo is archived (June 2026); "
            "the maintained successor is open-gsd/gsd-core."
        ),
    }


def build_next_steps(repo: dict, tools: dict, project: dict, frameworks: dict) -> list[str]:
    steps: list[str] = []
    # Reference the installed script by its real location so the printed
    # command works from a repo clone, a skills dir, or a plugin cache alike.
    init_script = Path(__file__).with_name("init_agents.py")
    init = (
        f"python3 {init_script} --cli both --claude-kit --project-root . "
        "(drop --claude-kit for non-Claude harnesses)"
    )

    if repo["v1_claude_layout"]:
        migrate_init = f"python3 {init_script} --cli both --claude-kit --skip-existing --project-root ."
        steps.append(
            "v1 layout detected (AGENTS.md is the old operational guide). Migrate: "
            "1) `git mv AGENTS.md OPS.md` to give the ops content its v2 home; "
            f"2) re-run init with --skip-existing to add the universal AGENTS.md bootloader and kit: {migrate_init}; "
            "3) optionally diff your CLAUDE.md against the new template via --stdout and merge improvements. "
            "Existing specs/, .workflow/, and memory-bank/ artifacts remain compatible — no changes needed."
        )
    elif repo["bootloader_claude"] == "missing" and repo["bootloader_codex"] == "missing":
        steps.append(f"Bootstrap agent files and the .claude kit: {init}")
    elif repo["bootloader_claude"] == "foreign" or repo["bootloader_codex"] == "foreign":
        steps.append(
            "Existing CLAUDE.md/AGENTS.md found (not generated by this skill). Do not overwrite: "
            "run init_agents.py with --stdout and merge the workflow section manually."
        )
        if not repo["kit_agents_present"]:
            steps.append(f"Install just the .claude kit alongside the existing files: {init}")
    elif not repo["kit_agents_present"]:
        steps.append(f"Bootloaders exist; add the .claude kit: {init}")

    if repo["kit_hooks_present"] and not repo["stop_gate_wired"]:
        steps.append(
            "Stop-gate hook script is installed but NOT wired into .claude/settings.json — the gate "
            "is not running. Merge the Stop hook entry from .claude/settings.json.template into "
            ".claude/settings.json."
        )
    if repo["kit_hooks_present"] and not repo["stop_gate_configured"]:
        steps.append(
            "Configure the stop gate: create .claude/stop-gate.json with this repo's test/lint "
            "commands so the agent cannot claim completion while checks fail."
        )

    if not repo["git_repo"]:
        steps.append("Not a git repo: run `git init` first — isolation, diffs, and worktrees depend on it.")

    if not tools["ripgrep"]["installed"]:
        steps.append("Install ripgrep (default search tool) — ask the user before installing.")
    if project.get("would_benefit_from_serena") and not tools["serena"]["installed"]:
        steps.append(
            "Large-codebase signals present and Serena missing: run large_codebase_tools.py --json "
            "and ask the user for approval to install/configure Serena."
        )

    if not frameworks["superpowers"]["installed"]:
        steps.append(
            "Install the Superpowers plugin (proven SDLC skills: brainstorming, TDD, plans, "
            f"subagent-driven dev): {SUPERPOWERS_INSTALL} — requires user approval."
        )
    if not frameworks["gsd"]["installed"]:
        steps.append(
            "Optional: GSD-style spec-driven commands via the maintained successor "
            f"({GSD_CORE_INSTALL}) — the original repo is archived; evaluate per "
            "pilot-measurement.md before adopting. Requires user approval."
        )

    if not steps:
        steps.append(
            "Setup complete. Compounding loop: run /retro at session end and /mint-skill when a "
            "workflow repeats."
        )
    return steps


def build_report(root: Path, home: Path | None = None) -> dict:
    home = home or Path.home()
    tools_module = load_sibling("large_codebase_tools")
    repo = check_repo(root)
    tools = tools_module.check_tools()
    project = tools_module.collect_project_signals(root, large_file_threshold=1000)
    frameworks = {
        "superpowers": detect_superpowers(home),
        "gsd": detect_gsd(root, home),
    }
    return {
        "mode": "read-only-preflight",
        "repo": repo,
        "project": {
            "file_count": project["file_count"],
            "languages": project["languages"],
            "large_codebase": project["large_codebase"],
            "would_benefit_from_serena": project["would_benefit_from_serena"],
        },
        "tools": {name: status["installed"] for name, status in tools.items() if status["checkable"]},
        "frameworks": frameworks,
        "next_steps": build_next_steps(repo, tools, project, frameworks),
        "safety": "No commands were executed except read-only git/plugin listings.",
    }


def print_human(report: dict) -> None:
    repo = report["repo"]
    print("Agentic workflow preflight")
    print(f"- Git repo: {repo['git_repo']}" + (" (dirty)" if repo["git_dirty"] else ""))
    print(f"- CLAUDE.md: {repo['bootloader_claude']}; AGENTS.md: {repo['bootloader_codex']}; OPS.md: {repo['ops']}")
    kit = f"{len(repo['kit_agents_present'])}/{len(KIT_AGENTS)} agents"
    kit += ", hooks" if repo["kit_hooks_present"] else ", no hooks"
    if not repo["stop_gate_wired"]:
        kit += ", stop gate NOT wired in settings.json"
    elif repo["stop_gate_configured"]:
        kit += ", stop gate wired + configured"
    else:
        kit += ", stop gate wired but no stop-gate.json"
    print(f"- .claude kit: {kit}")
    print(f"- Project: {report['project']['file_count']} files, languages: {', '.join(report['project']['languages']) or 'none detected'}")
    tools = ", ".join(f"{name}={'ok' if ok else 'missing'}" for name, ok in report["tools"].items())
    print(f"- Tools: {tools}")
    for name, framework in report["frameworks"].items():
        status = f"installed via {framework['detected_via']}" if framework["installed"] else "not installed"
        print(f"- {name}: {status}")
    print()
    print("Next steps (in order):")
    for index, step in enumerate(report["next_steps"], start=1):
        print(f"{index}. {step}")
    print()
    print(report["safety"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.project_root).resolve()
    if not root.is_dir():
        raise SystemExit(f"Project root does not exist or is not a directory: {root}")

    report = build_report(root)
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print_human(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
